language: php

os:
  - linux
  # PHP is no supported on OS X: https://github.com/travis-ci/travis-ci/issues/2313
  #- osx

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.3.3
      dist: precise

script:
  ### Generate
  - php generate --debug --testing < tests/generate_simple.txt
  - "[ -e test.dat ] && echo 'File test.dat exists' || (echo 'File test.dat not exists!!' && fake_command_to_stop_build)"
  - php generate --debug --testing < tests/generate_invalid_filename.txt
  - "[ -e test/valid_filename.dat ] && echo 'File test/valid_filename.dat exists' || (echo 'File test/valid_filename.dat not exists!!' && fake_command_to_stop_build)"
  - php generate --debug --testing < tests/generate_directory.txt
  - "[ -e test/test.dat ] && echo 'File test/test.dat exists' || (echo 'File test/test.dat not exists!!' && fake_command_to_stop_build)"
  - php generate --debug --testing < tests/generate_default_numbers.txt
  - "[ -e default_numbers.dat ] && echo 'File default_numbers.dat exists' || (echo 'File default_numbers.dat not exists!!' && fake_command_to_stop_build)"

  # Test for positive confirmation
  - php generate --debug --testing < tests/generate_simple.txt
  - php generate --debug --testing < tests/generate_negative_confirmation.txt

  # Generating large files
  - php generate --debug --testing < tests/generate_10MB_file.txt
  - "[ -e 10MB.dat ] && echo 'File 10MB.dat exists' || (echo 'File 10MB.dat not exists!!' && fake_command_to_stop_build)"
  - travis_wait php generate --min 5 --max 10 --decimal 6 --size 256MB --output 256MB --debug --testing
  - "[ -e 256MB.dat ] && echo 'File 256MB.dat exists' || (echo 'File 256MB.dat not exists!!' && fake_command_to_stop_build)"
  - travis_wait 30 php generate --min 5 --max 10 --decimal 6 --size 1GB --output 1GB --debug --testing
  - "[ -e 1GB.dat ] && echo 'File 1GB.dat exists' || (echo 'File 1GB.dat not exists!!' && fake_command_to_stop_build)"

  ### Sort
  - php sort --debug < tests/sort_simple.txt
  - "[ -e sort_test.dat ] && echo 'File sort_test.dat exists' || (echo 'File sort_test.dat not exists!!' && fake_command_to_stop_build)"
  - php sort --debug < tests/sort_10MB.txt
  - "[ -e sort_10MB.dat ] && echo 'File sort_10MB.dat exists' || (echo 'File sort_10MB.dat not exists!!' && fake_command_to_stop_build)"
  #- php sort --debug < tests/sort_256MB.txt
  #- "[ -e sort_256MB.dat ] && echo 'File sort_256MB.dat exists' || (echo 'File sort_256MB.dat not exists!!' && fake_command_to_stop_build)"

after_script:
  - rm *.dat
  - rm -rf test
