language: php

os:
  - linux
  # PHP is no supported on OS X: https://github.com/travis-ci/travis-ci/issues/2313
  #- osx

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

script:
  - php generate < tests/generate_simple.txt
  - "[ -e test.dat ] && echo 'File test.dat exists' || (echo 'File test.dat not exists!!' && fake_command_to_stop_build)"
  - php generate < tests/generate_directory.txt

after_script:
  - rm test.dat
  - rm test/test.dat
  - rmdir test
