language: php

os:
  - linux
  # PHP is no supported on OS X: https://github.com/travis-ci/travis-ci/issues/2313
  #- osx

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise

before_script:
  # Additional PHP config for increasing memory limit
  # See http://blog.simplytestable.com/setting-the-php-memory-limit-for-travis-ci/
  - phpenv config-add travis.php.ini

script:
  ### Generate
  - php generate -debug < tests/generate_simple.txt
  - "[ -e test.dat ] && echo 'File test.dat exists' || (echo 'File test.dat not exists!!' && fake_command_to_stop_build)"
  - php generate -debug < tests/generate_invalid_filename.txt
  - "[ -e bla\valid_filename.dat ] && echo 'File bla\valid_filename.dat exists' || (echo 'File bla\valid_filename.dat not exists!!' && fake_command_to_stop_build)"
  - php generate -debug < tests/generate_directory.txt
  - "[ -e test/test.dat ] && echo 'File test/test.dat exists' || (echo 'File test/test.dat not exists!!' && fake_command_to_stop_build)"
  - php generate -debug < tests/generate_default_numbers.txt
  - "[ -e default_numbers.dat ] && echo 'File default_numbers.dat exists' || (echo 'File default_numbers.dat not exists!!' && fake_command_to_stop_build)"

  # Test for positive confirmation
  - php generate -debug < tests/generate_simple.txt
  - php generate -debug < tests/generate_negative_confirmation.txt

  # Generating large files
  - php generate -debug -testing < tests/generate_10MB_file.txt
  - "[ -e 10MB.dat ] && echo 'File 10MB.dat exists' || (echo 'File 10MB.dat not exists!!' && fake_command_to_stop_build)"
  #- php generate -debug -testing < tests/generate_1GB_file.txt
  #- "[ -e 1GB.dat ] && echo 'File 1GB.dat exists' || (echo 'File 1GB.dat not exists!!' && fake_command_to_stop_build)"

after_script:
  - rm test.dat
  - rm bla\valid_filename.dat
  - rm test/test.dat
  - rmdir test
  - rm default_numbers.dat
  - rm 10MB.dat
  #- rm 1GB.dat
