#!/usr/bin/env php
<?php
/**
 * Generate script.
 *
 * Generates file with randomized floating numbers.
 *
 * @author  Adam "Saibamen" Stachowicz <saibamenppl@gmail.com>
 */

// Run only in CLI
if (php_sapi_name() !== 'cli') {
    exit('This is console app. Please run it in console (CLI)!');
}

/*
 * If true - print more information.
 *
 * @var bool
 *
 * @todo Read from console arguments
 */
define('DEBUG', true);

require_once 'generate.inc.php';

$min = getNumberInput('Type minimum allowed number');
$max = getNumberInput('Type maximum allowed number', 10);

// Switch min and max if min > max
$minMax = checkSwitchMinMax($min, $max);

$min = $minMax['min'];
$max = $minMax['max'];

$decimalPlaces = getNumberInput('Type number of decimal places');

// TODO: File size to generate

$filename = getFilenameInput('Type output filename (without extension)');

$outputString = generateRandomNumbers($min, $max, $decimalPlaces);

saveStringToFile($outputString, $filename);
