#!/usr/bin/env php
<?php
/**
 * Generate script.
 *
 * Generates file with randomized floating numbers.
 *
 * @author  Adam "Saibamen" Stachowicz <saibamenppl@gmail.com>
 * @license MIT
 *
 * @link    https://github.com/Saibamen/Generate-Sort-Numbers
 */

namespace Generate;

use Includes\File;
use Includes\Generate;
use Includes\Input;
use Includes\Text;

require_once 'Includes/Generate.php';
require_once 'Includes/Input.php';
require_once 'Includes/File.php';

// Run only in CLI
if (php_sapi_name() !== 'cli') {
    exit('This is console app. Please run it in console (CLI)!');
}

// Check for -debug command
if (isset($argv[1]) && $argv[1] === '-debug') {
    Text::message('Debug mode. Have fun!');
    Text::setDebug(true);
}

$min = Input::getNumberInput('Type minimum allowed number');
$max = Input::getNumberInput('Type maximum allowed number', 10);

// Switch min and max if min > max
$minMax = Generate::checkSwitchMinMax($min, $max);

$min = $minMax['min'];
$max = $minMax['max'];

$decimalPlaces = Input::getNumberInput('Type number of decimal places');

// TODO: File size to generate
$fileSize = (int) Input::getNumberInput('Type maximum file size (in bytes)', 123);

$outputString = Generate::generateRandomNumbers($min, $max, $decimalPlaces, $fileSize);

$filename = Input::getFilenameInput('Type output filename (without extension)');
File::saveStringToFile($outputString, $filename);
