#!/usr/bin/env php
<?php
/**
 * Generate script.
 *
 * Generates file with randomized floating numbers.
 *
 * @author  Adam "Saibamen" Stachowicz <saibamenppl@gmail.com>
 * @license MIT
 *
 * @link    https://github.com/Saibamen/Generate-Sort-Numbers
 */

namespace Generate;

use Includes\Generate;
use Includes\Input;
use Includes\Text;

// Run only in CLI
if (php_sapi_name() !== 'cli') {
    exit('This is console app. Please run it in console (CLI)!');
}

// Increase the memory limit
ini_set('memory_limit', '1024M');

require_once 'Includes/Generate.php';
require_once 'Includes/Input.php';
require_once 'Includes/File.php';

// Check for console arguments
if (count($argv) > 1) {
    foreach ($argv as $arg) {
        switch ($arg) {
            case '-debug':
                Text::message('Debug mode. Have fun!');
                Text::setDebug(true);
                break;
            case '-testing':
                Text::message('Testing mode');
                Generate::setTesting(true);
                break;
        }
    }
}

$min = Input::getNumberInput('Type minimum allowed number');
$max = Input::getNumberInput('Type maximum allowed number', 10);

// Switch min and max if min > max
$minMax = Generate::checkSwitchMinMax($min, $max);

$min = $minMax['min'];
$max = $minMax['max'];

$decimalPlaces = Input::getNumberInput('Type number of decimal places');

$fileSize = Input::getFileSizeInput("Type maximum file size\nie. `5B`, `5KB`, `5MB`, `5GB`");

$filename = Input::getFilenameInput('Type output filename (without extension)');

Generate::generateRandomNumbers($min, $max, $decimalPlaces, $fileSize, $filename);

//File::saveStringToFile($outputString, $filename);
