# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.8-browsers

    steps:
      - checkout

      - run: sudo apt-get update

      - run:
          name: Display versions
          command: |
            php -v

      - run: php generate < tests/generate_simple.txt
      - run: php generate < tests/generate_directory.txt
